config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :actions

  get '/token' => 'token#token'

  get '/current_list' => 'actions#current_list'
  get '/history' => 'actions#history'

end

app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :actions

end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  before_action :find_user

  def index
    actions = @user.actions
    # these are priority actions
    @priority_actions = actions.where(priority: true).order("time_estimated").reverse
    nonpriority = actions.where(priority: false)
    # these are the nonpriority actions
    @sorted_actions = nonpriority.order("time_estimated").reverse
    # @all_sorted_actions = actions.order("time_estimated")
    render :index
  end

  def new
    @actions = @user.actions.new
    render :new
  end

  def create
    @actions = @user.actions.create(action_params)
    if @actions
      render json: {status: "success"}
    else
      render json: {status: "error"}
    end
  end

  def current_list
    @time_est = params[:time_available]
    actions = @user.actions.where("time_estimated <= ? AND is_completed = ?", @time_est, false)
    # these are priority actions that are at or below the time available
    @priority_actions = actions.where(priority: true).order("time_estimated").reverse
    nonpriority = actions.where(priority: false, is_completed: false)
    # these are the nonpriority actions that are at or below the time available
    @sorted_actions = nonpriority.order("time_estimated").reverse
  end

  def update
    @action = Action.find(params[:id])
    if params[:update] === "start"
      if @action.update({time_started:Time.now})
        render json: {status: "success"}
      else
        render json: {status: "error"}
      end
    elsif params[:update] === "stop"
      @action.update({time_finished: Time.now, is_completed: true})
      @total_time = hour_min(@action.time_finished,@action.time_started)
      @action.update({time_took: @total_time}) # won't store bc the schema is expecting an integer. We need to store it as an array or string
      time_obj = {
        estimated_time: @action.time_estimated,
        total_time: @total_time
      }
      if @total_time
        render json: {time_metrics: time_obj, status: "success"}
      else
        render json: {status: "error"}
      end

    end
  end

  def history
      @history = @user.actions.where("is_completed = ?", true)
      render :history
  end

  def destroy
    @action = Action.find(params[:id])
    @action.destroy
    if @action.destroy
      render json: {status: "success"}
    else
      render json: {status: "error"}
    end
  end

  private

  def hour_min(last,first)

   difference = last - first
   seconds    =  difference % 60
   difference = (difference - seconds) / 60
   minutes    =  difference % 60
   difference = (difference - minutes) / 60
   hours      =  difference % 24

   return hours,minutes,seconds

 end


  def action_params
    params.permit(:notes, :time_estimated, :action_name, :priority)
  end

  def find_user
    @user = User.find(current_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


# place after_sign_in_path_for here in the application contoller

private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email) }
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @user = find_user
    @token_value = session["_csrf_token"]
		render :index
	end

  private

    def find_user
      @user = User.find(current_user)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(users)
    new_action_path
  end

  def after_inactive_sign_up_path_for(users)
    new_action_path
  end

  def after_sign_in_path_for(users)
    root_path
  end

end

app/controllers/token_controller.rb
class TokenController < ApplicationController
  def token
    generate_token
  end

  private
  def generate_token
    token = session["_csrf_token"]
    render :json => token
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/Home/index.html.erb
<%= render "layouts/header"%>
<div class="container">
	<div class="jumbotron col-md-offset-3 col-md-6">
				<h2 class="time-header text-left">How much time do you have?</h2>
		<div>
<!-- 				<input type="text" class="col-sm-3 form-control" name="current-time"></input> -->
<form class="form-horizontal" action= "/current_list" method= "get" id="new-task-form">
	<div class="form-group">
        <label class="col-sm-2 control-label">Minutes</label>
        <div class= "col-sm-10">
          <button type="radio" id="btn-0" name="time_available" value= "5" class="btn btn-default ">5</button>
          <button type="radio" id="btn-1" name="time_available" value= "10"class="btn btn-default">10</button>
          <button type="radio" id="btn-2" name="time_available" value= "20"class="btn btn-default ">20</button>
          <button type="radio" id="btn-3" name="time_available" value= "30"class="btn btn-default ">30</button>
          <button type="radio" id="btn-4" name="time_available" value= "40"class="btn btn-default ">40</button>
          <button type="radio" id="btn-5" name="time_available" value= "50"class="btn btn-default ">50</button>
          <button type="radio" id="btn-6" name="time_available" value= "60"class="btn btn-default ">60</button>
        </div>
      </div>
			</form>
		</div>
	</div>
</div>
    

app/views/actions/current_list.html.erb
<%=  render 'layouts/header'%>
<div class="container">



	<h1 class="col-sm-offset-3 col-sm-9 header-current-time">With <%= @time_est %> minutes you could: </h1>


	<!-- if action is a priority -->

	<% @priority_actions.each do |priority| %>
	<div id="div<%=priority.id%>" class="action-div priority col-sm-offset-2 col-sm-8 text-left">
			<h3 class="action" id="<%= priority.id %>"><%= priority.action_name%></h3>
			<p class= "time-foot text-right"><%=priority.time_estimated%></p>
			<div class="clicker-div">
				<p>Notes: <%= priority.notes%></p>
				<p class="action-time">Time estimated: <%= priority.time_estimated%></p>
				<button class="doButton" id="<%=priority.id%>" type="button" data-toggle="modal" data-target="#modal<%=priority.id%>" class="btn btn-default select-task">Do this task.</button>
			</div>
		</div>
	<% end %>




	<% @sorted_actions.each do |sorted| %>

	<% if sorted.time_estimated === 60 %>
		<div id="div<%=sorted.id%>" class="action-div sixty col-sm-offset-2 col-sm-8 text-left">
			<h3 class="action" id="<%= sorted.id %>"><%= sorted.action_name%></h3>
			<p class= "time-foot text-right"><%=sorted.time_estimated%></p>
			<div class="clicker-div">
				<p>Notes: <%= sorted.notes%></p>
				<p>Time estimated: <%= sorted.time_estimated%></p>
				<button class="doButton" id="<%=sorted.id%>" type="button" data-toggle="modal" data-target="#modal<%=sorted.id%>" class="btn btn-default select-task">Do this task.</button>
			</div>
		</div>
	<% elsif sorted.time_estimated === 50 %>
		<div id="div<%=sorted.id%>" class="action-div fifty col-sm-offset-2 col-sm-8 text-left">
			<h3 class="action" id="<%= sorted.id %>"><%= sorted.action_name%></h3>
			<p class= "time-foot text-right"><%=sorted.time_estimated%></p>
			<div class="clicker-div">
				<p>Notes: <%= sorted.notes%></p>
				<p>Time estimated: <%= sorted.time_estimated%></p>
				<button class="doButton" id="<%=sorted.id%>" type="button" data-toggle="modal" data-target="#modal<%=sorted.id%>" class="btn btn-default select-task">Do this task.</button>
			</div>
		</div>
	<% elsif sorted.time_estimated === 40 %>
		<div id="div<%=sorted.id%>" class="action-div forty col-sm-offset-2 col-sm-8 text-left">
			<h3 class="action" id="<%= sorted.id %>"><%= sorted.action_name%></h3>
			<p class= "time-foot text-right"><%=sorted.time_estimated%></p>
			<div class="clicker-div">
				<p>Notes: <%= sorted.notes%></p>
				<p>Time estimated: <%= sorted.time_estimated%></p>
				<button class="doButton" id="<%=sorted.id%>" type="button" data-toggle="modal" data-target="#modal<%=sorted.id%>" class="btn btn-default select-task">Do this task.</button>
			</div>
		</div>
	<% elsif sorted.time_estimated === 30 %>
		<div id="div<%=sorted.id%>" class="action-div thirty col-sm-offset-2 col-sm-8 text-left">
			<h3 class="action" id="<%= sorted.id %>"><%= sorted.action_name%></h3>
			<p class= "time-foot text-right"><%=sorted.time_estimated%></p>
			<div class="clicker-div">
				<p>Notes: <%= sorted.notes%></p>
				<p>Time estimated: <%= sorted.time_estimated%></p>
				<button class="doButton" id="<%=sorted.id%>" type="button" data-toggle="modal" data-target="#modal<%=sorted.id%>" class="btn btn-default select-task">Do this task.</button>
			</div>
		</div>
	<% elsif sorted.time_estimated === 20 %>
		<div id="div<%=sorted.id%>" class="action-div twenty col-sm-offset-2 col-sm-8 text-left">
			<h3 class="action" id="<%= sorted.id %>"><%= sorted.action_name%></h3>
			<p class= "time-foot text-right"><%=sorted.time_estimated%></p>
			<div class="clicker-div">
				<p>Notes: <%= sorted.notes%></p>
				<p>Time estimated: <%= sorted.time_estimated%></p>
				<button class="doButton" id="<%=sorted.id%>" type="button" data-toggle="modal" data-target="#modal<%=sorted.id%>" class="btn btn-default select-task">Do this task.</button>
			</div>
		</div>
	<% elsif sorted.time_estimated === 10 %>
		<div id="div<%=sorted.id%>" class="action-div ten col-sm-offset-2 col-sm-8 text-left">
			<h3 class="action" id="<%= sorted.id %>"><%= sorted.action_name%></h3>
			<p class= "time-foot text-right"><%=sorted.time_estimated%></p>
			<div class="clicker-div">
				<p>Notes: <%= sorted.notes%></p>
				<p>Time estimated: <%= sorted.time_estimated%></p>
				<button class="doButton" id="<%=sorted.id%>" type="button" data-toggle="modal" data-target="#modal<%=sorted.id%>" class="btn btn-default select-task">Do this task.</button>
			</div>
		</div>
	<% elsif sorted.time_estimated === 5 %>
		<div id="div<%=sorted.id%>" class="action-div five col-sm-offset-2 col-sm-8 text-left">
			<h3 class="action" id="<%= sorted.id %>"><%= sorted.action_name%></h3>
			<p class= "time-foot text-right"><%=sorted.time_estimated%></p>
			<div class="clicker-div">
				<p>Notes: <%= sorted.notes%></p>
				<p>Time estimated: <%= sorted.time_estimated%></p>
				<button class="doButton" id="<%=sorted.id%>" type="button" data-toggle="modal" data-target="#modal<%=sorted.id%>" class="btn btn-default select-task">Do this task.</button>
			</div>
		</div>
	<% end %>
	<% end %>
	<script charset="utf-8">
		collapsableList();
		grabStartButtons();
	</script>

</div>

<!-- TIMER MODAL -->
<% @priority_actions.each do |priority| %>
<div class="modal fade" id="modal<%=priority.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Task: <%= priority.action_name%></h3>
      </div>
			<div id="modal<%=priority.id%>Body" class="modal-body ">
				<h4 class= "modal-head-time">You have estimated <%=priority.time_estimated%> minutes for this task.</h4>
				<!-- <div id="modal<%=priority.id%>progressBar%>" class="progressBar">

				</div> -->
				<div class="progress progressBar">
	  			<div class="progress-bar progress-bar-striped active firstP" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
				</div>
				<div class="progress progressBar">
					<div class="progress-bar progress-bar-striped active secondP" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
				</div>
				<div class="progress progressBar">
					<div class="progress-bar progress-bar-striped active thirdP" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
				</div>
				<div class="progress progressBar">
					<div class="progress-bar progress-bar-striped active fourthP" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
				</div>
				<div class="progress progressBar">
					<div class="progress-bar progress-bar-striped active fifthP" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
				</div>
				<div class="returnedTime">

				</div><br>
				<button id="modal<%=priority.id%>button" data-id="<%=priority.id%>" type="button" class="btn btn-default stop-task">Finished</button>
			</div>
    </div>
  </div>
</div>
<% end %>
<% @sorted_actions.each do |sorted| %>
<div class="modal fade" id="modal<%=sorted.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Task: <%=sorted.action_name%></h3>
      </div>
			<div id="modal<%=sorted.id%>Body" class="modal-body ">
				<h4 class= "modal-head-time">You have estimated <%=sorted.time_estimated%> minutes for this task.</h4>
				<!-- <div id="modal<%=sorted.id%>progressBar%>" class="progressBar">

				</div> -->
				<div class="progress progressBar">
	  			<div class="progress-bar progress-bar-striped active firstP" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
				</div>
				<div class="progress progressBar">
					<div class="progress-bar progress-bar-striped active secondP" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
				</div>
				<div class="progress progressBar">
					<div class="progress-bar progress-bar-striped active thirdP" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
				</div>
				<div class="progress progressBar">
					<div class="progress-bar progress-bar-striped active fourthP" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
				</div>
				<div class="progress progressBar">
					<div class="progress-bar progress-bar-striped active fifthP" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
				</div>
				<div class="returnedTime">

				</div> <br>
				<button id="modal<%=sorted.id%>button" data-id="<%=sorted.id%>" type="button" class="btn btn-default stop-task">Finished</button>
			</div>
    </div>
  </div>
</div>
<% end %>

app/views/actions/history.html.erb
<%=  render 'layouts/header' %>
<!-- foreach through list add listener and display name and est. time -->

<div class="container">

    <h1 class="col-sm-offset-3 col-sm-9 header-current-time">Job well done! </h1>

  <!-- if action is a priority -->

  <% @history.each do |action| %>
  <% if action.time_estimated === 60 %>
    <div class="action-div action-entire-list sixty col-sm-offset-2 col-sm-8 text-left" draggable="true" id="<%= action.id %>">
      <p class="x text-right"><%= link_to 'X', action, method: :delete, :remote => true, :class => 'delete_action' %></p>
      <h3 class="action" id="<%= action.id %>"><%= action.action_name%></h3>
      <p class= "time-foot text-right">Real Time: <%=action.time_took%></p>
      <div class="clicker-div">
        <p>Notes: <%= action.notes%></p>
        <p>Time: <%= action.time_estimated%></p>
      </div>
    </div>
  <% elsif action.time_estimated === 50 %>
    <div class="action-div action-entire-list fifty col-sm-offset-2 col-sm-8 text-left" draggable="true" id="<%= action.id %>">
      <p class="x text-right"><%= link_to 'X', action, method: :delete, :remote => true, :class => 'delete_action' %></p>
      <h3 class="action" id="<%= action.id %>"><%= action.action_name%></h3>
      <p class= "time-foot text-right">Real Time: <%=action.time_took%></p>
      <div class="clicker-div">
        <p>Notes: <%= action.notes%></p>
        <p>Time: <%= action.time_estimated%></p>
      </div>
    </div>
  <% elsif action.time_estimated === 40 %>
    <div class="action-div action-entire-list forty col-sm-offset-2 col-sm-8 text-left" draggable="true" id="<%= action.id %>">
      <p class="x text-right"><%= link_to 'X', action, method: :delete, :remote => true, :class => 'delete_action' %></p>
      <h3 class="action" id="<%= action.id %>"><%= action.action_name%></h3>
      <p class= "time-foot text-right">Real Time: <%=action.time_took%></p>
      <div class="clicker-div">
        <p>Notes: <%= action.notes%></p>
        <p>Time: <%= action.time_estimated%></p>
      </div>
    </div>
  <% elsif action.time_estimated === 30 %>
    <div class="action-div action-entire-list thirty col-sm-offset-2 col-sm-8 text-left" draggable="true" id="<%= action.id %>">
      <p class="x text-right"><%= link_to 'X', action, method: :delete, :remote => true, :class => 'delete_action' %></p>
      <h3 class="action" id="<%= action.id %>"><%= action.action_name%></h3>
      <p class= "time-foot text-right">Real Time: <%=action.time_took%></p>
      <div class="clicker-div">
        <p>Notes: <%= action.notes%></p>
        <p>Time: <%= action.time_estimated%></p>
      </div>
    </div>
  <% elsif action.time_estimated === 20 %>
    <div class="action-div action-entire-list twenty col-sm-offset-2 col-sm-8 text-left" draggable="true" id="<%= action.id %>">
      <p class="x text-right"><%= link_to 'X', action, method: :delete, :remote => true, :class => 'delete_action' %></p>
      <h3 class="action" id="<%= action.id %>"><%= action.action_name%></h3>
      <p class= "time-foot text-right">Real Time: <%=action.time_took%></p>
      <div class="clicker-div">
        <p>Notes: <%= action.notes%></p>
        <p>Time: <%= action.time_estimated%></p>
      </div>
    </div>
  <% elsif action.time_estimated === 10 %>
    <div class="action-div action-entire-list ten col-sm-offset-2 col-sm-8 text-left" draggable="true" id="<%= action.id %>">
      <p class="x text-right"><%= link_to 'X', action, method: :delete, :remote => true, :class => 'delete_action' %></p>
      <h3 class="action" id="<%= action.id %>"><%= action.action_name%></h3>
      <p class= "time-foot text-right">Real Time: <%=action.time_took%></p>
      <div class="clicker-div">
        <p>Notes: <%= action.notes%></p>
        <p>Time: <%= action.time_estimated%></p>
      </div>
    </div>
  <% elsif action.time_estimated === 5 %>
    <div class="action-div action-entire-list five col-sm-offset-2 col-sm-8 text-left" draggable="true" id="<%= action.id %>">
      <p class="x text-right"><%= link_to 'X', action, method: :delete, :remote => true, :class => 'delete_action' %></p>
      <h3 class="action" id="<%= action.id %>"><%= action.action_name%></h3>
      <p class= "time-foot text-right">Real Time: <%=action.time_took%></p>
      <div class="clicker-div">
        <p>Notes: <%= action.notes%></p>
        <p>Time: <%= action.time_estimated%></p>
      </div>
    </div>
  <% end %>
  <% end %>
</div>
<script charset="utf-8">
  collapsableList();
</script>

app/views/actions/new.html.erb
<%=  render 'layouts/header' %>

<div class="container">
  <div class="row">
    <div class='col-sm-offset-3 col-sm-6'>

      <h1 class='col-sm-offset-2'>Add A New Task</h1>



      <!-- user_registration POST   /users(.:format)               devise/registrations#create -->

      <form class="form-horizontal" action= "/actions" method= "post" id="new-task-form">

        <div class="form-group">
          <label class="col-sm-2 control-label">Task</label>
          <div class="col-sm-10">
            <input type="text" id="action-name" name= "action_name" class="form-control"  placeholder="Name">
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label">Notes</label>
          <div class="col-sm-10">
            <input type="text" id="action-notes" name="notes" class="form-control"  placeholder="Notes">
          </div>
        </div>


        <div class="form-group">
          <label class="col-sm-2 control-label">Estimate (mins)</label>
          <div class="col-sm-10">
            <span type="radio" id="btn-0" name="time_estimated" class="btn btn-default ">5</span>
            <span type="radio" id="btn-1" name="time_estimated" class="btn btn-default">10</span>
            <span type="radio" id="btn-2" name="time_estimated" class="btn btn-default ">20</span>
            <span type="radio" id="btn-3" name="time_estimated" class="btn btn-default ">30</span>
            <span type="radio" id="btn-4" name="time_estimated" class="btn btn-default ">40</span>
            <span type="radio" id="btn-5" name="time_estimated" class="btn btn-default ">50</span>
            <span type="radio" id="btn-6" name="time_estimated" class="btn btn-default ">60</span>
            <span type="radio" id="btn-7" name="time_estimated" class="btn btn-default ">Don't know</span>
          </div>

      </div>

      <div class=" form-group">
          <div class="col-md-offset-2 col-md-10">
              <input type="checkbox" name="priority" id="priority-check">
              <label for="priority-check">Priority</label>
              <p class="whisper">Priority items will be surfaced at the top of your list.</p>
          </div>
      </div>


        <script type="text/javascript">
          taskTimeSelector();
        </script>
        <div class="form-group">

            <div class="col-md-offset-4 col-md-6">


              <button type="button" class="btn btn-default addTaskButton" id="add-new-task">Add Task</button>

              <script charset="utf-8">
                addTaskListener();
              </script>
            </div>
          </div>

      </form>
    </div>
  </div>
  <div class="row" id= "task-list-div"></div>
</div>

app/views/actions/show.html.erb
<%= render "layouts/header"%>


<!-- <div class="container">
	<div class="jumbotron col-md-offset-3 col-md-6">
		<h2 class="col-md-offset-3 col-md-6"><#%= @action.action_name %></h2>
			<div class="col-sm-offset-3 col-sm-6 col-md-offset-3 col-md-6" id="stopwatch">00:00:00</div>
		<div class="col-md-offset-3 col-md-6">
				<button id="start" class="btn btn-default">Start</button>
				<button id="stop" class="btn btn-default">Pause</button>
	</div>
</div> -->

app/views/home/index.html.erb
<%= render "layouts/header"%>

	<div class="jumbotron col-md-offset-2 col-md-8">
				<h2 class="header-current-time text-center">How many minutes do you have?</h2>

		<div>
<!-- 				<input type="text" class="col-sm-3 form-control" name="current-time"></input> -->
<form class="form-horizontal" action= "/current_list" method= "get" id="new-task-form">
	<div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class= "col-sm-8 text-center">
          <button type="radio" id="btn-0" name="time_available" value= "5" class="btn btn-default btn-lg ">5</button>
          <button type="radio" id="btn-1" name="time_available" value= "10"class="btn btn-default btn-lg">10</button>
          <button type="radio" id="btn-2" name="time_available" value= "20"class="btn btn-default btn-lg">20</button>
          <button type="radio" id="btn-3" name="time_available" value= "30"class="btn btn-default btn-lg">30</button>
          <button type="radio" id="btn-4" name="time_available" value= "40"class="btn btn-default btn-lg">40</button>
          <button type="radio" id="btn-5" name="time_available" value= "50"class="btn btn-default btn-lg">50</button>
          <button type="radio" id="btn-6" name="time_available" value= "60"class="btn btn-default btn-lg">60</button>
        </div>
      </div>


        <script type="text/javascript">
          // breakTimeSelector();
        </script>


			</form>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default nav-barfixed-top  text-center" id="top-nav-main">
	<div class="container-flid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" id="brand-name" href="/">RealTime</a><script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		</div>

		<div class="collapse navbar-collapse" id="main-nav">
			<ul class="nav navbar-nav navbar-right">
				<li id="add-task-button">
					<%= link_to "Add Task", new_action_path %>
				</li>
				<li>
					<%= link_to "Do A Task", root_path %>
				</li>
				<li class="dropdown">
					<a href="#" id="menu-button" class-"dropdown-toggle" data-toggle="dropdown" role="button" aria-expand="false">Menu<span class="caret"></span></a>
					<ul id="menu-list" class="dropdown-menu" role="menu">
						<li><%= link_to "List", actions_path(@user) %></li>
						<li><%= link_to "My History", history_path(@user) %></li>
						<li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "log out"%></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RealTime</title>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>